# ./docker-compose.yml
version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: .dockerFile
    ports:
      - "3000:3000" # Map port 3000 on the host to port 3000 in the container
    env_file:
      - .env
    secrets:
      - apikey
      - serviceAccountKey
    restart: always

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD_FILE=/run/secrets/redis_password
    secrets:
      - redis_password
      - redis_username
    restart: always

secrets:
  apikey:
    external: true
  redis_password:
    external: true
  redis_username:
    external: true
  serviceAccountKey:
    external: true
